export const SET_PRODUCT_NAME = 'set_product_name'
export const SET_PRODUCT_PRICE = 'set_product_price'
export const SET_PRODUCT_BRAND = 'set_product_brand'
export const SET_PRODUCT_IMAGE = 'set_product_image'
export const ADD_PRODUCT = 'add_product'
